import React, { createContext, useContext, useState } from 'react';

type Language = 'en' | 'nl' | 'de' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.about': 'About',
    'nav.services': 'Services',
    'nav.portfolio': 'Portfolio',
    'nav.getStarted': 'Get Started',
    
    // Hero
    'hero.title1': 'Your professional website,',
    'hero.title2': 'fully taken care of.',
    'hero.description': 'We build a powerful website for your business at lightning speed and handle everything: from design and hosting to monthly maintenance. You run your business, we handle the internet.',
    'hero.startProject': 'View our approach',
    'hero.viewWork': 'View Our Work',
    'hero.ideas.biography': 'Personal Biography',
    'hero.ideas.blog': 'Blog Site',
    'hero.ideas.portfolio': 'Portfolio Website',
    'hero.ideas.shop': 'Online Shop',
    'hero.ideas.cafe': 'Café Website',
    'hero.ideas.salon': 'Salon Page',
    'hero.ideas.services': 'Service Business',
    'hero.ideas.gallery': 'Art Gallery',
    'hero.ideas.contact': 'Contact Page',
    'hero.ideas.landing': 'Landing Page',
    
    // Services
    'services.title': 'Our All-in-One',
    'services.titleAccent': 'Package',
    'services.subtitle': 'Everything you need for a successful online presence.',
    'services.design.title': 'Design & Development',
    'services.design.desc': 'A custom-built, mobile-friendly website. Including 2 feedback rounds so the design is 100% to your liking.',
    'services.hosting.title': 'Hosting & Domain',
    'services.hosting.desc': 'We register your domain name, arrange a secure server (SSL) and ensure your website always loads lightning fast.',
    'services.maintenance.title': 'Monthly Maintenance',
    'services.maintenance.desc': 'Ongoing technical updates, security and support for small adjustments. Your website is always up-to-date.',
    'services.photo.title': 'Business Photography (Optional)',
    'services.photo.desc': 'No professional photos? No problem. We come to your location to capture your team, office or products in sharp detail. Perfectly optimized for your new website.',
    
    // Pricing
    'pricing.addon.title': 'Optional Add-ons',
    'pricing.addon.photo': 'Website Photography Package',
    'pricing.addon.photoPrice': '+ € 200,- (one-time)',
    'pricing.addon.photoDesc': '1.5 hour on-location shoot, 15-20 edited photos, including unlimited usage rights for your own marketing.',

    // Portfolio
    'portfolio.title': 'Featured',
    'portfolio.titleAccent': 'Work',
    'portfolio.subtitle': 'Transforming ideas into exceptional digital experiences',
    'portfolio.project1.title': 'Personal Website',
    'portfolio.project1.category': 'Biography',
    'portfolio.project1.desc': 'Personal biography website showcasing my story, interests, and journey in technology.',
    'portfolio.project2.title': 'ATLAZ',
    'portfolio.project2.category': 'DJ Website',
    'portfolio.project2.desc': 'Official DJ website featuring mixes, upcoming shows, and press info.',
    'portfolio.project3.title': 'Hytale Vlaanderen',
    'portfolio.project3.category': 'Community Platform',
    'portfolio.project3.desc': 'Flemish community hub for a Hytale server hosted by the best Flemish Twitch streamers.',
    'portfolio.project4.title': 'Webdesign Portfolio',
    'portfolio.project4.category': 'Portfolio',
    'portfolio.project4.desc': 'A school project showcasing my webdesign skills and creative projects.',
    
    // About
    'about.title': 'About',
    'about.titleAccent': 'FlipForward',
    'about.subtitle': 'Your digital partner for websites without hassle',
    'about.description': "FlipForward is your digital partner that bridges the gap between technology and design. We don't believe in complicated processes, but in speed, transparency and quality. With a passion for the latest web technologies, we build websites that are not only beautiful but also work perfectly on every device.",
    'about.passion.title': 'Lightning Fast Live',
    'about.passion.desc': 'Online within 5 business days, as soon as we have received your texts and images.',
    'about.learning.title': 'Fully Managed',
    'about.learning.desc': 'No hassle with servers or updates; we manage your hosting and technology.',
    'about.dedication.title': 'Premium Design',
    'about.dedication.desc': 'Modern, conversion-focused designs that strengthen your brand.',
    
    // Pricing
    'pricing.title': 'WaaS Package',
    'pricing.titleAccent': '(Website as a Service)',
    'pricing.setup': '€ 1.000,-',
    'pricing.setupLabel': 'one-time setup',
    'pricing.monthly': '+ € 50,- / month',
    'pricing.monthlyLabel': '(maintenance & hosting)',
    'pricing.feature1': 'Complete web design (max. 5 pages)',
    'pricing.feature2': 'Including domain name & premium hosting',
    'pricing.feature3': 'Delivery in 5 business days',
    'pricing.feature4': 'Responsive on mobile & tablet',
    'pricing.feature5': 'Basic SEO optimization',
    'pricing.feature6': 'Monthly technical updates',
    'pricing.feature7': 'Support for small changes (<30 min/month)',
    'pricing.cta': 'Start your project',

    // Contact
    'contact.title': "Let's Build Something",
    'contact.titleAccent': 'Amazing',
    'contact.subtitle': "Ready to flip your business forward? Get in touch with us today.",
    'contact.name': 'Your Name',
    'contact.namePlaceholder': 'John Doe',
    'contact.email': 'Email Address',
    'contact.emailPlaceholder': 'john@example.com',
    'contact.message': 'Your Message',
    'contact.messagePlaceholder': 'Tell us about your project...',
    'contact.send': 'Send Message',
    'contact.emailUs': 'Email Us',
    'contact.delivery': 'Fast Delivery',
    'contact.deliveryDesc': 'We prioritize quick turnaround times without compromising on quality.',
    'contact.visuals': 'Visual Excellence',
    'contact.visualsDesc': 'Creating beautiful, modern designs that make your project stand out.',
    'contact.success': 'Message Sent!',
    'contact.successDesc': "We'll get back to you within 24 hours.",
    'contact.requestTitle': 'Request a Website',
    'contact.requestDesc': 'Create an account and submit a detailed website request. Track the status and receive updates.',
    'contact.requestCta': 'Submit a request',
    'contact.requestCtaSignup': 'Create account & request',

    // Terms
    'terms.title': 'Terms & Conditions FlipForward',
    'terms.lastUpdated': 'Last updated',
    'terms.intro': 'These terms and conditions apply to all offers, quotes, and agreements between FlipForward (part of the sole proprietorship Finn Vangronsveld / ATLAZ Records, KBO: BE1033868758) and the Client.',
    'terms.art1.title': 'Article 1: The "Website as a Service" (WaaS) Model',
    'terms.art1.p1': 'FlipForward delivers web design and hosting through a subscription model. The Client does not purchase the website but obtains an exclusive right of use as long as the monthly subscription is active.',
    'terms.art1.p2': 'All websites developed by FlipForward, including code, designs, AI implementations, and licenses, remain the intellectual property of FlipForward at all times.',
    'terms.art2.title': 'Article 2: Delivery and Content',
    'terms.art2.p1': 'FlipForward aims to deliver the initial website (Proof of Concept) within 5 business days. This period only begins after the startup invoice has been paid and all required content (texts, images, logos) has been provided by the Client.',
    'terms.art2.p2': 'If the Client fails to provide material in a timely manner, this may delay the delivery period. This does not entitle the Client to a discount or compensation.',
    'terms.art2.p3': 'A maximum of two (2) feedback rounds are included in the initial build.',
    'terms.art3.title': 'Article 3: Subscription and Maintenance',
    'terms.art3.p1': 'After the website goes live or is approved, the monthly subscription of €50 (excl. VAT) begins.',
    'terms.art3.p2': 'This subscription includes hosting, domain name registration, license costs for tools used, and minor technical maintenance up to a maximum of 30 minutes per month.',
    'terms.art3.p3': 'Modifications that fall outside the initial scope or take longer than 30 minutes (additional work) will be invoiced after consultation at an hourly rate of €100 (excl. VAT).',
    'terms.art4.title': 'Article 4: Payment and Default',
    'terms.art4.p1': 'Invoices must be paid within 14 days of the invoice date.',
    'terms.art4.p2': 'If payment is not received after this period, the Client will receive a reminder. If payment remains outstanding, FlipForward is entitled to (temporarily) take the website offline until the full amount has been paid.',
    'terms.art4.p3': 'Startup costs must be paid prior to the commencement of work.',
    'terms.art5.title': 'Article 5: Cancellation of Subscription',
    'terms.art5.p1': 'The subscription can be cancelled monthly by the Client.',
    'terms.art5.p2': 'Upon cancellation, the right of use referred to in Article 1 expires. The website and associated files will be permanently removed from the servers at the end of the current billing period. No transfer of code or website files to the Client will take place.',
    'terms.art6.title': 'Article 6: Liability',
    'terms.art6.p1': 'FlipForward endeavors to ensure the website and linked AI tools function optimally but cannot guarantee 100% uptime or error-free operation of external (AI) software.',
    'terms.art6.p2': 'The liability of FlipForward for direct or indirect damage is at all times limited to a maximum of the invoice amount of the past three (3) months of the relevant assignment.',
    'terms.art7.title': 'Article 7: Applicable Law',
    'terms.art7.p1': 'All agreements between FlipForward and the Client are exclusively governed by Belgian law. Disputes will be submitted to the competent court in the district where FlipForward is established.',

    // Privacy Policy
    'privacy.title': 'Privacy Policy FlipForward',
    'privacy.lastUpdated': 'Last updated',
    'privacy.intro': 'FlipForward (part of ATLAZ Records, KBO: BE1033868758) values your privacy. In this privacy policy, we explain which personal data we collect, why we do this, and what your rights are.',
    'privacy.section1.title': '1. What data do we collect?',
    'privacy.section1.text': 'When you fill in our contact form or purchase a web design subscription from us, we collect the following data:',
    'privacy.section1.items': 'First and last name|Company name and KBO/VAT number|Email address and phone number|Billing and payment details',
    'privacy.section2.title': '2. Why do we collect this data?',
    'privacy.section2.text': 'We use your data exclusively for:',
    'privacy.section2.items': 'Building, hosting, and maintaining your website.|Processing payments and invoicing (via our partner Dexxter).|Contacting you about your project or support questions.',
    'privacy.section3.title': '3. How long do we keep your data?',
    'privacy.section3.text': 'We do not retain your personal data longer than strictly necessary to achieve the purposes for which your data is collected. Billing data is legally retained for 7 years to comply with Belgian tax legislation.',
    'privacy.section4.title': '4. Sharing data with third parties',
    'privacy.section4.text': 'FlipForward does not sell your data to third parties and only provides it if this is necessary for the execution of our agreement with you (for example, hosting parties or invoicing software) or to comply with a legal obligation.',
    'privacy.section5.title': '5. Your rights (GDPR)',
    'privacy.section5.text': 'You have the right to view, correct, or delete your personal data. In addition, you have the right to withdraw any consent for data processing or to object to the processing of your personal data by FlipForward. Please send an email to: info@flipforward.be.',
    'privacy.section6.title': '6. Cookies',
    'privacy.section6.text': 'Our website uses functional cookies to ensure the website works optimally. We also use analytics tools to analyze how visitors use our website.',
  },
  nl: {
    // Navigation
    'nav.about': 'Over',
    'nav.services': 'Diensten',
    'nav.portfolio': 'Portfolio',
    'nav.getStarted': 'Begin Nu',
    
    // Hero
    'hero.title1': 'Jouw professionele website,',
    'hero.title2': 'volledig ontzorgd.',
    'hero.description': 'Wij bouwen razendsnel een krachtige website voor jouw bedrijf en regelen alles: van design en hosting tot het maandelijkse onderhoud. Jij onderneemt, wij regelen het internet.',
    'hero.startProject': 'Bekijk onze werkwijze',
    'hero.viewWork': 'Bekijk Ons Werk',
    'hero.ideas.biography': 'Persoonlijke Biografie',
    'hero.ideas.blog': 'Blog Site',
    'hero.ideas.portfolio': 'Portfolio Website',
    'hero.ideas.shop': 'Online Winkel',
    'hero.ideas.cafe': 'Café Website',
    'hero.ideas.salon': 'Salon Pagina',
    'hero.ideas.services': 'Diensten Bedrijf',
    'hero.ideas.gallery': 'Kunst Galerij',
    'hero.ideas.contact': 'Contact Pagina',
    'hero.ideas.landing': 'Landing Pagina',
    
    // Services
    'services.title': 'Ons All-in-One',
    'services.titleAccent': 'Pakket',
    'services.subtitle': 'Alles wat je nodig hebt voor een succesvolle online aanwezigheid.',
    'services.design.title': 'Design & Ontwikkeling',
    'services.design.desc': 'Een op maat gemaakte, mobielvriendelijke website. Inclusief 2 feedbackrondes zodat het design 100% naar wens is.',
    'services.hosting.title': 'Hosting & Domein',
    'services.hosting.desc': 'Wij registreren jouw domeinnaam, regelen een veilige server (SSL) en zorgen dat je website altijd bliksemsnel laadt.',
    'services.maintenance.title': 'Maandelijks Onderhoud',
    'services.maintenance.desc': 'Doorlopende technische updates, beveiliging en support voor kleine aanpassingen. Jouw website is altijd up-to-date.',
    
    // Portfolio
    'portfolio.title': 'Uitgelicht',
    'portfolio.titleAccent': 'Werk',
    'portfolio.subtitle': 'Ideeën omzetten in uitzonderlijke digitale ervaringen',
    'portfolio.project1.title': 'Persoonlijke Website',
    'portfolio.project1.category': 'Biografie',
    'portfolio.project1.desc': 'Persoonlijke biografie website die mijn verhaal, interesses en reis in technologie toont.',
    'portfolio.project2.title': 'ATLAZ',
    'portfolio.project2.category': 'DJ Website',
    'portfolio.project2.desc': 'Officiële DJ-website met mixes, aankomende shows en presskit.',
    'portfolio.project3.title': 'Hytale Vlaanderen',
    'portfolio.project3.category': 'Community Platform',
    'portfolio.project3.desc': 'Vlaamse community hub voor een Hytale-server, gehost door de beste Vlaamse Twitch-streamers.',
    'portfolio.project4.title': 'Webdesign Portfolio',
    'portfolio.project4.category': 'Portfolio',
    'portfolio.project4.desc': 'Een school project dat mijn webdesign vaardigheden en creatieve projecten toont.',
    
    // About
    'about.title': 'Over',
    'about.titleAccent': 'FlipForward',
    'about.subtitle': 'Jouw digitale partner voor websites zonder gedoe',
    'about.description': 'FlipForward is jouw digitale partner die de brug slaat tussen techniek en design. Wij geloven niet in ingewikkelde trajecten, maar in snelheid, transparantie en kwaliteit. Met een passie voor de nieuwste webtechnologieën bouwen we websites die niet alleen prachtig zijn, maar ook perfect werken op elk apparaat.',
    'about.passion.title': 'Razendsnel Live',
    'about.passion.desc': 'Binnen 5 werkdagen online, zodra wij jouw teksten en beelden hebben ontvangen.',
    'about.learning.title': 'Volledig Ontzorgd',
    'about.learning.desc': 'Geen gedoe met servers of updates; wij beheren je hosting en techniek.',
    'about.dedication.title': 'Premium Design',
    'about.dedication.desc': 'Moderne, conversiegerichte ontwerpen die jouw merk versterken.',
    
    // Pricing
    'pricing.title': 'WaaS Pakket',
    'pricing.titleAccent': '(Website as a Service)',
    'pricing.setup': '€ 1.000,-',
    'pricing.setupLabel': 'eenmalige setup',
    'pricing.monthly': '+ € 50,- / maand',
    'pricing.monthlyLabel': '(onderhoud & hosting)',
    'pricing.feature1': 'Compleet webdesign (max. 5 pagina\'s)',
    'pricing.feature2': 'Inclusief domeinnaam & premium hosting',
    'pricing.feature3': 'Oplevering in 5 werkdagen',
    'pricing.feature4': 'Responsive op mobiel & tablet',
    'pricing.feature5': 'Basis SEO-optimalisatie',
    'pricing.feature6': 'Maandelijkse technische updates',
    'pricing.feature7': 'Support voor kleine wijzigingen (<30 min/mnd)',
    'pricing.cta': 'Start jouw project',

    // Contact
    'contact.title': 'Laten We Iets',
    'contact.titleAccent': 'Geweldigs Bouwen',
    'contact.subtitle': 'Klaar om jouw bedrijf vooruit te helpen? Neem vandaag nog contact met ons op.',
    'contact.name': 'Jouw Naam',
    'contact.namePlaceholder': 'Jan de Vries',
    'contact.email': 'E-mailadres',
    'contact.emailPlaceholder': 'jan@voorbeeld.nl',
    'contact.message': 'Jouw Bericht',
    'contact.messagePlaceholder': 'Vertel ons over jouw project...',
    'contact.send': 'Verzend Bericht',
    'contact.emailUs': 'E-mail Ons',
    'contact.delivery': 'Snelle Levering',
    'contact.deliveryDesc': 'Wij geven prioriteit aan snelle doorlooptijden zonder concessies te doen aan kwaliteit.',
    'contact.visuals': 'Visuele Excellence',
    'contact.visualsDesc': 'Prachtige, moderne ontwerpen creëren die jouw project laten opvallen.',
    'contact.success': 'Bericht Verzonden!',
    'contact.successDesc': 'We nemen binnen 24 uur contact met je op.',
    'contact.requestTitle': 'Website Aanvragen',
    'contact.requestDesc': 'Maak een account aan en dien een gedetailleerde website-aanvraag in. Volg de status en ontvang updates.',
    'contact.requestCta': 'Aanvraag indienen',
    'contact.requestCtaSignup': 'Account maken & aanvragen',

    // Terms
    'terms.title': 'Algemene Voorwaarden FlipForward',
    'terms.lastUpdated': 'Laatst bijgewerkt',
    'terms.intro': 'Deze algemene voorwaarden zijn van toepassing op alle aanbiedingen, offertes en overeenkomsten tussen FlipForward (onderdeel van de eenmanszaak Finn Vangronsveld / ATLAZ Records, KBO: BE1033868758) en de Opdrachtgever.',
    'terms.art1.title': 'Artikel 1: Het "Website as a Service" (WaaS) Model',
    'terms.art1.p1': 'FlipForward levert webdesign en hosting aan de hand van een abonnementsmodel. De Opdrachtgever koopt de website niet, maar verkrijgt een exclusief gebruiksrecht zolang het maandelijkse abonnement actief is.',
    'terms.art1.p2': 'Alle door FlipForward ontwikkelde websites, inclusief code, ontwerpen, AI-implementaties en licenties, blijven te allen tijde intellectueel eigendom van FlipForward.',
    'terms.art2.title': 'Artikel 2: Oplevering en Inhoud',
    'terms.art2.p1': 'FlipForward streeft naar een oplevering van de initiële website (Proof of Concept) binnen 5 werkdagen. Deze termijn gaat pas in nadat de opstartfactuur is voldaan én alle benodigde inhoud (teksten, afbeeldingen, logo\'s) door de Opdrachtgever is aangeleverd.',
    'terms.art2.p2': 'Indien de Opdrachtgever nalaat tijdig materiaal aan te leveren, kan dit de oplevertermijn vertragen. Dit geeft geen recht op korting of schadevergoeding.',
    'terms.art2.p3': 'Bij de initiële bouw zijn maximaal twee (2) feedbackrondes inbegrepen.',
    'terms.art3.title': 'Artikel 3: Abonnement en Onderhoud',
    'terms.art3.p1': 'Na de livegang of goedkeuring van de website start het maandelijkse abonnement van € 50,- (excl. BTW).',
    'terms.art3.p2': 'Dit abonnement omvat hosting, domeinnaamregistratie, licentiekosten voor gebruikte tools, en klein technisch onderhoud tot maximaal 30 minuten per maand.',
    'terms.art3.p3': 'Aanpassingen die buiten de initiële scope vallen of langer dan 30 minuten in beslag nemen (meerwerk), worden na overleg gefactureerd tegen het uurtarief van € 100,- (excl. BTW).',
    'terms.art4.title': 'Artikel 4: Betaling en Wanbetaling',
    'terms.art4.p1': 'Facturen dienen binnen 14 dagen na factuurdatum te worden voldaan.',
    'terms.art4.p2': 'Bij het uitblijven van betaling na deze termijn, ontvangt de Opdrachtgever een herinnering. Blijft betaling daarna uit, dan is FlipForward gerechtigd de website (tijdelijk) offline te halen tot het volledige bedrag is voldaan.',
    'terms.art4.p3': 'Opstartkosten dienen voorafgaand aan de start van de werkzaamheden te worden voldaan.',
    'terms.art5.title': 'Artikel 5: Opzegging van het Abonnement',
    'terms.art5.p1': 'Het abonnement is maandelijks opzegbaar door de Opdrachtgever.',
    'terms.art5.p2': 'Bij opzegging vervalt het in Artikel 1 genoemde gebruiksrecht. De website en bijbehorende bestanden worden aan het einde van de lopende facturatieperiode permanent van de servers verwijderd. Er vindt geen overdracht van code of websitebestanden naar de Opdrachtgever plaats.',
    'terms.art6.title': 'Artikel 6: Aansprakelijkheid',
    'terms.art6.p1': 'FlipForward spant zich in om de website en gekoppelde AI-tools optimaal te laten functioneren, maar kan geen 100% uptime of foutloze werking van externe (AI-)software garanderen.',
    'terms.art6.p2': 'De aansprakelijkheid van FlipForward voor directe of indirecte schade is te allen tijde beperkt tot maximaal het factuurbedrag van de afgelopen drie (3) maanden van de desbetreffende opdracht.',
    'terms.art7.title': 'Artikel 7: Toepasselijk Recht',
    'terms.art7.p1': 'Op alle overeenkomsten tussen FlipForward en de Opdrachtgever is uitsluitend het Belgisch recht van toepassing. Geschillen zullen worden voorgelegd aan de bevoegde rechtbank in het arrondissement waar FlipForward is gevestigd.',

    // Privacy Policy
    'privacy.title': 'Privacybeleid FlipForward',
    'privacy.lastUpdated': 'Laatst bijgewerkt',
    'privacy.intro': 'FlipForward (onderdeel van ATLAZ Records, KBO: BE1033868758) hecht veel waarde aan jouw privacy. In dit privacybeleid leggen we uit welke persoonsgegevens we verzamelen, waarom we dit doen en wat jouw rechten zijn.',
    'privacy.section1.title': '1. Welke gegevens verzamelen we?',
    'privacy.section1.text': 'Wanneer je ons contactformulier invult of een abonnement voor webdesign bij ons afneemt, verzamelen we de volgende gegevens:',
    'privacy.section1.items': 'Voor- en achternaam|Bedrijfsnaam en KBO/BTW-nummer|E-mailadres en telefoonnummer|Facturatie- en betaalgegevens',
    'privacy.section2.title': '2. Waarom verzamelen we deze gegevens?',
    'privacy.section2.text': 'Wij gebruiken jouw gegevens uitsluitend voor:',
    'privacy.section2.items': 'Het bouwen, hosten en onderhouden van jouw website.|Het afhandelen van betalingen en facturatie (via onze partner Dexxter).|Om contact met je op te nemen over je project of supportvragen.',
    'privacy.section3.title': '3. Hoe lang bewaren we je gegevens?',
    'privacy.section3.text': 'We bewaren je persoonsgegevens niet langer dan strikt nodig is om de doelen te realiseren waarvoor je gegevens worden verzameld. Facturatiegegevens worden wettelijk 7 jaar bewaard ter voldoening aan de Belgische belastingwetgeving.',
    'privacy.section4.title': '4. Delen van gegevens met derden',
    'privacy.section4.text': 'FlipForward verkoopt jouw gegevens niet aan derden en verstrekt deze uitsluitend indien dit nodig is voor de uitvoering van onze overeenkomst met jou (bijvoorbeeld hostingpartijen of facturatiesoftware) of om te voldoen aan een wettelijke verplichting.',
    'privacy.section5.title': '5. Jouw rechten (GDPR)',
    'privacy.section5.text': 'Je hebt het recht om je persoonsgegevens in te zien, te corrigeren of te verwijderen. Daarnaast heb je het recht om je eventuele toestemming voor de gegevensverwerking in te trekken of bezwaar te maken tegen de verwerking van jouw persoonsgegevens door FlipForward. Stuur hiervoor een e-mail naar: info@flipforward.be.',
    'privacy.section6.title': '6. Cookies',
    'privacy.section6.text': 'Onze website maakt gebruik van functionele cookies om de website optimaal te laten werken. Ook gebruiken wij analysetools om te analyseren hoe bezoekers onze website gebruiken.',
  },
  de: {
    // Navigation
    'nav.about': 'Über uns',
    'nav.services': 'Leistungen',
    'nav.portfolio': 'Portfolio',
    'nav.getStarted': 'Loslegen',
    
    // Hero
    'hero.title1': 'Ihre professionelle Website,',
    'hero.title2': 'komplett betreut.',
    'hero.description': 'Wir erstellen blitzschnell eine leistungsstarke Website für Ihr Unternehmen und kümmern uns um alles: von Design und Hosting bis zur monatlichen Wartung. Sie führen Ihr Geschäft, wir regeln das Internet.',
    'hero.startProject': 'Unsere Arbeitsweise',
    'hero.viewWork': 'Unsere Arbeit ansehen',
    'hero.ideas.biography': 'Persönliche Biografie',
    'hero.ideas.blog': 'Blog-Seite',
    'hero.ideas.portfolio': 'Portfolio-Website',
    'hero.ideas.shop': 'Online-Shop',
    'hero.ideas.cafe': 'Café-Website',
    'hero.ideas.salon': 'Salon-Seite',
    'hero.ideas.services': 'Dienstleistungen',
    'hero.ideas.gallery': 'Kunstgalerie',
    'hero.ideas.contact': 'Kontaktseite',
    'hero.ideas.landing': 'Landingpage',
    
    // Services
    'services.title': 'Unser All-in-One',
    'services.titleAccent': 'Paket',
    'services.subtitle': 'Alles, was Sie für eine erfolgreiche Online-Präsenz brauchen.',
    'services.design.title': 'Design & Entwicklung',
    'services.design.desc': 'Eine maßgeschneiderte, mobilfreundliche Website. Inklusive 2 Feedbackrunden, damit das Design 100% Ihren Wünschen entspricht.',
    'services.hosting.title': 'Hosting & Domain',
    'services.hosting.desc': 'Wir registrieren Ihren Domainnamen, richten einen sicheren Server (SSL) ein und sorgen dafür, dass Ihre Website immer blitzschnell lädt.',
    'services.maintenance.title': 'Monatliche Wartung',
    'services.maintenance.desc': 'Laufende technische Updates, Sicherheit und Support für kleine Anpassungen. Ihre Website ist immer auf dem neuesten Stand.',
    
    // Portfolio
    'portfolio.title': 'Ausgewählte',
    'portfolio.titleAccent': 'Arbeiten',
    'portfolio.subtitle': 'Ideen in außergewöhnliche digitale Erlebnisse verwandeln',
    'portfolio.project1.title': 'Persönliche Website',
    'portfolio.project1.category': 'Biografie',
    'portfolio.project1.desc': 'Persönliche Biografie-Website, die meine Geschichte, Interessen und meinen Weg in der Technologie zeigt.',
    'portfolio.project2.title': 'ATLAZ',
    'portfolio.project2.category': 'DJ-Website',
    'portfolio.project2.desc': 'Offizielle DJ-Website mit Mixes, kommenden Shows und Presseinformationen.',
    'portfolio.project3.title': 'Hytale Vlaanderen',
    'portfolio.project3.category': 'Community-Plattform',
    'portfolio.project3.desc': 'Flämischer Community-Hub für einen Hytale-Server, gehostet von den besten flämischen Twitch-Streamern.',
    'portfolio.project4.title': 'Webdesign Portfolio',
    'portfolio.project4.category': 'Portfolio',
    'portfolio.project4.desc': 'Ein Schulprojekt, das meine Webdesign-Fähigkeiten und kreativen Projekte präsentiert.',
    
    // About
    'about.title': 'Über',
    'about.titleAccent': 'FlipForward',
    'about.subtitle': 'Ihr digitaler Partner für Websites ohne Aufwand',
    'about.description': 'FlipForward ist Ihr digitaler Partner, der die Brücke zwischen Technologie und Design schlägt. Wir glauben nicht an komplizierte Prozesse, sondern an Geschwindigkeit, Transparenz und Qualität. Mit einer Leidenschaft für die neuesten Webtechnologien bauen wir Websites, die nicht nur schön sind, sondern auch auf jedem Gerät perfekt funktionieren.',
    'about.passion.title': 'Blitzschnell Live',
    'about.passion.desc': 'Innerhalb von 5 Werktagen online, sobald wir Ihre Texte und Bilder erhalten haben.',
    'about.learning.title': 'Komplett Betreut',
    'about.learning.desc': 'Kein Aufwand mit Servern oder Updates; wir verwalten Ihr Hosting und Ihre Technik.',
    'about.dedication.title': 'Premium Design',
    'about.dedication.desc': 'Moderne, conversionorientierte Designs, die Ihre Marke stärken.',
    
    // Pricing
    'pricing.title': 'WaaS-Paket',
    'pricing.titleAccent': '(Website as a Service)',
    'pricing.setup': '€ 1.000,-',
    'pricing.setupLabel': 'einmalige Einrichtung',
    'pricing.monthly': '+ € 50,- / Monat',
    'pricing.monthlyLabel': '(Wartung & Hosting)',
    'pricing.feature1': 'Komplettes Webdesign (max. 5 Seiten)',
    'pricing.feature2': 'Inklusive Domainname & Premium-Hosting',
    'pricing.feature3': 'Lieferung in 5 Werktagen',
    'pricing.feature4': 'Responsive auf Mobilgeräten & Tablets',
    'pricing.feature5': 'Basis-SEO-Optimierung',
    'pricing.feature6': 'Monatliche technische Updates',
    'pricing.feature7': 'Support für kleine Änderungen (<30 Min./Monat)',
    'pricing.cta': 'Projekt starten',

    // Contact
    'contact.title': 'Lassen Sie uns etwas',
    'contact.titleAccent': 'Großartiges bauen',
    'contact.subtitle': 'Bereit, Ihr Unternehmen voranzubringen? Kontaktieren Sie uns noch heute.',
    'contact.name': 'Ihr Name',
    'contact.namePlaceholder': 'Max Mustermann',
    'contact.email': 'E-Mail-Adresse',
    'contact.emailPlaceholder': 'max@beispiel.de',
    'contact.message': 'Ihre Nachricht',
    'contact.messagePlaceholder': 'Erzählen Sie uns von Ihrem Projekt...',
    'contact.send': 'Nachricht senden',
    'contact.emailUs': 'E-Mail an uns',
    'contact.delivery': 'Schnelle Lieferung',
    'contact.deliveryDesc': 'Wir legen Wert auf schnelle Bearbeitungszeiten ohne Kompromisse bei der Qualität.',
    'contact.visuals': 'Visuelle Exzellenz',
    'contact.visualsDesc': 'Wunderschöne, moderne Designs, die Ihr Projekt hervorheben.',
    'contact.success': 'Nachricht gesendet!',
    'contact.successDesc': 'Wir melden uns innerhalb von 24 Stunden bei Ihnen.',
    'contact.requestTitle': 'Website Anfragen',
    'contact.requestDesc': 'Erstellen Sie ein Konto und reichen Sie eine detaillierte Website-Anfrage ein. Verfolgen Sie den Status und erhalten Sie Updates.',
    'contact.requestCta': 'Anfrage einreichen',
    'contact.requestCtaSignup': 'Konto erstellen & anfragen',

    // Terms
    'terms.title': 'Allgemeine Geschäftsbedingungen FlipForward',
    'terms.lastUpdated': 'Zuletzt aktualisiert',
    'terms.intro': 'Diese Allgemeinen Geschäftsbedingungen gelten für alle Angebote, Kostenvoranschläge und Vereinbarungen zwischen FlipForward (Teil des Einzelunternehmens Finn Vangronsveld / ATLAZ Records, KBO: BE1033868758) und dem Auftraggeber.',
    'terms.art1.title': 'Artikel 1: Das „Website as a Service" (WaaS) Modell',
    'terms.art1.p1': 'FlipForward liefert Webdesign und Hosting über ein Abonnementmodell. Der Auftraggeber erwirbt die Website nicht, sondern erhält ein exklusives Nutzungsrecht, solange das monatliche Abonnement aktiv ist.',
    'terms.art1.p2': 'Alle von FlipForward entwickelten Websites, einschließlich Code, Designs, KI-Implementierungen und Lizenzen, bleiben jederzeit geistiges Eigentum von FlipForward.',
    'terms.art2.title': 'Artikel 2: Lieferung und Inhalt',
    'terms.art2.p1': 'FlipForward strebt die Lieferung der initialen Website (Proof of Concept) innerhalb von 5 Werktagen an. Diese Frist beginnt erst, nachdem die Startrechnung bezahlt wurde und alle erforderlichen Inhalte (Texte, Bilder, Logos) vom Auftraggeber bereitgestellt wurden.',
    'terms.art2.p2': 'Wenn der Auftraggeber es versäumt, Material rechtzeitig bereitzustellen, kann dies die Lieferfrist verzögern. Dies berechtigt nicht zu einem Rabatt oder einer Entschädigung.',
    'terms.art2.p3': 'Im initialen Bau sind maximal zwei (2) Feedbackrunden enthalten.',
    'terms.art3.title': 'Artikel 3: Abonnement und Wartung',
    'terms.art3.p1': 'Nach der Liveschaltung oder Genehmigung der Website beginnt das monatliche Abonnement von 50 € (zzgl. MwSt.).',
    'terms.art3.p2': 'Dieses Abonnement umfasst Hosting, Domainnamenregistrierung, Lizenzkosten für verwendete Tools und kleinere technische Wartung bis maximal 30 Minuten pro Monat.',
    'terms.art3.p3': 'Änderungen, die außerhalb des ursprünglichen Umfangs liegen oder länger als 30 Minuten dauern (Mehrarbeit), werden nach Absprache zum Stundensatz von 100 € (zzgl. MwSt.) in Rechnung gestellt.',
    'terms.art4.title': 'Artikel 4: Zahlung und Verzug',
    'terms.art4.p1': 'Rechnungen sind innerhalb von 14 Tagen nach Rechnungsdatum zu begleichen.',
    'terms.art4.p2': 'Bleibt die Zahlung nach dieser Frist aus, erhält der Auftraggeber eine Mahnung. Bleibt die Zahlung weiterhin aus, ist FlipForward berechtigt, die Website (vorübergehend) offline zu nehmen, bis der volle Betrag bezahlt ist.',
    'terms.art4.p3': 'Die Startkosten sind vor Beginn der Arbeiten zu entrichten.',
    'terms.art5.title': 'Artikel 5: Kündigung des Abonnements',
    'terms.art5.p1': 'Das Abonnement kann vom Auftraggeber monatlich gekündigt werden.',
    'terms.art5.p2': 'Bei Kündigung erlischt das in Artikel 1 genannte Nutzungsrecht. Die Website und zugehörige Dateien werden am Ende des laufenden Abrechnungszeitraums dauerhaft von den Servern entfernt. Eine Übertragung von Code oder Website-Dateien an den Auftraggeber findet nicht statt.',
    'terms.art6.title': 'Artikel 6: Haftung',
    'terms.art6.p1': 'FlipForward bemüht sich, die Website und verknüpfte KI-Tools optimal funktionieren zu lassen, kann jedoch keine 100%ige Verfügbarkeit oder fehlerfreie Funktion externer (KI-)Software garantieren.',
    'terms.art6.p2': 'Die Haftung von FlipForward für direkte oder indirekte Schäden ist jederzeit auf maximal den Rechnungsbetrag der letzten drei (3) Monate des betreffenden Auftrags beschränkt.',
    'terms.art7.title': 'Artikel 7: Anwendbares Recht',
    'terms.art7.p1': 'Auf alle Vereinbarungen zwischen FlipForward und dem Auftraggeber ist ausschließlich belgisches Recht anwendbar. Streitigkeiten werden dem zuständigen Gericht im Bezirk vorgelegt, in dem FlipForward seinen Sitz hat.',

    // Privacy Policy
    'privacy.title': 'Datenschutzerklärung FlipForward',
    'privacy.lastUpdated': 'Zuletzt aktualisiert',
    'privacy.intro': 'FlipForward (Teil von ATLAZ Records, KBO: BE1033868758) schätzt Ihre Privatsphäre. In dieser Datenschutzerklärung erklären wir, welche personenbezogenen Daten wir erheben, warum wir dies tun und welche Rechte Sie haben.',
    'privacy.section1.title': '1. Welche Daten erheben wir?',
    'privacy.section1.text': 'Wenn Sie unser Kontaktformular ausfüllen oder ein Webdesign-Abonnement bei uns abschließen, erheben wir folgende Daten:',
    'privacy.section1.items': 'Vor- und Nachname|Firmenname und KBO/USt.-Nummer|E-Mail-Adresse und Telefonnummer|Rechnungs- und Zahlungsdaten',
    'privacy.section2.title': '2. Warum erheben wir diese Daten?',
    'privacy.section2.text': 'Wir verwenden Ihre Daten ausschließlich für:',
    'privacy.section2.items': 'Erstellung, Hosting und Wartung Ihrer Website.|Zahlungsabwicklung und Rechnungsstellung (über unseren Partner Dexxter).|Kontaktaufnahme bezüglich Ihres Projekts oder Supportfragen.',
    'privacy.section3.title': '3. Wie lange bewahren wir Ihre Daten auf?',
    'privacy.section3.text': 'Wir bewahren Ihre personenbezogenen Daten nicht länger auf, als es zur Erreichung der Zwecke, für die Ihre Daten erhoben werden, unbedingt erforderlich ist. Rechnungsdaten werden gesetzlich 7 Jahre aufbewahrt, um der belgischen Steuergesetzgebung zu entsprechen.',
    'privacy.section4.title': '4. Weitergabe von Daten an Dritte',
    'privacy.section4.text': 'FlipForward verkauft Ihre Daten nicht an Dritte und gibt sie nur weiter, wenn dies für die Durchführung unserer Vereinbarung mit Ihnen erforderlich ist (z. B. Hosting-Anbieter oder Rechnungssoftware) oder um einer gesetzlichen Verpflichtung nachzukommen.',
    'privacy.section5.title': '5. Ihre Rechte (DSGVO)',
    'privacy.section5.text': 'Sie haben das Recht, Ihre personenbezogenen Daten einzusehen, zu korrigieren oder zu löschen. Darüber hinaus haben Sie das Recht, eine erteilte Einwilligung zur Datenverarbeitung zu widerrufen oder der Verarbeitung Ihrer personenbezogenen Daten durch FlipForward zu widersprechen. Senden Sie hierzu eine E-Mail an: info@flipforward.be.',
    'privacy.section6.title': '6. Cookies',
    'privacy.section6.text': 'Unsere Website verwendet funktionale Cookies, um die optimale Funktion der Website zu gewährleisten. Wir verwenden auch Analysetools, um zu analysieren, wie Besucher unsere Website nutzen.',
  },
  fr: {
    // Navigation
    'nav.about': 'À propos',
    'nav.services': 'Services',
    'nav.portfolio': 'Portfolio',
    'nav.getStarted': 'Commencer',
    
    // Hero
    'hero.title1': 'Votre site web professionnel,',
    'hero.title2': 'entièrement pris en charge.',
    'hero.description': 'Nous créons un site web performant pour votre entreprise à la vitesse de l\'éclair et nous occupons de tout : du design et de l\'hébergement à la maintenance mensuelle. Vous gérez votre activité, nous gérons Internet.',
    'hero.startProject': 'Notre approche',
    'hero.viewWork': 'Voir nos réalisations',
    'hero.ideas.biography': 'Biographie personnelle',
    'hero.ideas.blog': 'Site Blog',
    'hero.ideas.portfolio': 'Site Portfolio',
    'hero.ideas.shop': 'Boutique en ligne',
    'hero.ideas.cafe': 'Site Café',
    'hero.ideas.salon': 'Page Salon',
    'hero.ideas.services': 'Entreprise de services',
    'hero.ideas.gallery': 'Galerie d\'art',
    'hero.ideas.contact': 'Page de contact',
    'hero.ideas.landing': 'Page d\'atterrissage',
    
    // Services
    'services.title': 'Notre forfait',
    'services.titleAccent': 'tout-en-un',
    'services.subtitle': 'Tout ce dont vous avez besoin pour une présence en ligne réussie.',
    'services.design.title': 'Design & Développement',
    'services.design.desc': 'Un site web sur mesure et adapté aux mobiles. Comprenant 2 tours de feedback pour que le design soit 100% à votre goût.',
    'services.hosting.title': 'Hébergement & Domaine',
    'services.hosting.desc': 'Nous enregistrons votre nom de domaine, mettons en place un serveur sécurisé (SSL) et garantissons que votre site se charge toujours à la vitesse de l\'éclair.',
    'services.maintenance.title': 'Maintenance mensuelle',
    'services.maintenance.desc': 'Mises à jour techniques continues, sécurité et support pour les petits ajustements. Votre site web est toujours à jour.',
    
    // Portfolio
    'portfolio.title': 'Travaux',
    'portfolio.titleAccent': 'en vedette',
    'portfolio.subtitle': 'Transformer les idées en expériences numériques exceptionnelles',
    'portfolio.project1.title': 'Site personnel',
    'portfolio.project1.category': 'Biographie',
    'portfolio.project1.desc': 'Site biographique personnel présentant mon histoire, mes intérêts et mon parcours technologique.',
    'portfolio.project2.title': 'ATLAZ',
    'portfolio.project2.category': 'Site DJ',
    'portfolio.project2.desc': 'Site officiel de DJ avec des mixes, des événements à venir et des infos presse.',
    'portfolio.project3.title': 'Hytale Vlaanderen',
    'portfolio.project3.category': 'Plateforme communautaire',
    'portfolio.project3.desc': 'Hub communautaire flamand pour un serveur Hytale hébergé par les meilleurs streamers Twitch flamands.',
    'portfolio.project4.title': 'Portfolio Webdesign',
    'portfolio.project4.category': 'Portfolio',
    'portfolio.project4.desc': 'Un projet scolaire présentant mes compétences en webdesign et mes projets créatifs.',
    
    // About
    'about.title': 'À propos de',
    'about.titleAccent': 'FlipForward',
    'about.subtitle': 'Votre partenaire numérique pour des sites web sans tracas',
    'about.description': 'FlipForward est votre partenaire numérique qui fait le pont entre la technologie et le design. Nous ne croyons pas aux processus compliqués, mais à la rapidité, la transparence et la qualité. Passionnés par les dernières technologies web, nous créons des sites qui sont non seulement beaux mais fonctionnent aussi parfaitement sur chaque appareil.',
    'about.passion.title': 'En ligne ultra-rapide',
    'about.passion.desc': 'En ligne dans les 5 jours ouvrables, dès réception de vos textes et images.',
    'about.learning.title': 'Entièrement géré',
    'about.learning.desc': 'Aucun souci avec les serveurs ou les mises à jour ; nous gérons votre hébergement et votre technique.',
    'about.dedication.title': 'Design Premium',
    'about.dedication.desc': 'Des designs modernes et orientés conversion qui renforcent votre marque.',
    
    // Pricing
    'pricing.title': 'Forfait WaaS',
    'pricing.titleAccent': '(Website as a Service)',
    'pricing.setup': '€ 1.000,-',
    'pricing.setupLabel': 'mise en place unique',
    'pricing.monthly': '+ € 50,- / mois',
    'pricing.monthlyLabel': '(maintenance & hébergement)',
    'pricing.feature1': 'Design web complet (max. 5 pages)',
    'pricing.feature2': 'Nom de domaine & hébergement premium inclus',
    'pricing.feature3': 'Livraison en 5 jours ouvrables',
    'pricing.feature4': 'Responsive sur mobile & tablette',
    'pricing.feature5': 'Optimisation SEO de base',
    'pricing.feature6': 'Mises à jour techniques mensuelles',
    'pricing.feature7': 'Support pour petites modifications (<30 min/mois)',
    'pricing.cta': 'Démarrer votre projet',

    // Contact
    'contact.title': 'Construisons quelque chose',
    'contact.titleAccent': 'd\'incroyable',
    'contact.subtitle': 'Prêt à propulser votre entreprise ? Contactez-nous dès aujourd\'hui.',
    'contact.name': 'Votre nom',
    'contact.namePlaceholder': 'Jean Dupont',
    'contact.email': 'Adresse e-mail',
    'contact.emailPlaceholder': 'jean@exemple.fr',
    'contact.message': 'Votre message',
    'contact.messagePlaceholder': 'Parlez-nous de votre projet...',
    'contact.send': 'Envoyer le message',
    'contact.emailUs': 'Envoyez-nous un e-mail',
    'contact.delivery': 'Livraison rapide',
    'contact.deliveryDesc': 'Nous privilégions des délais rapides sans compromettre la qualité.',
    'contact.visuals': 'Excellence visuelle',
    'contact.visualsDesc': 'Créer des designs beaux et modernes qui font ressortir votre projet.',
    'contact.success': 'Message envoyé !',
    'contact.successDesc': 'Nous vous répondrons dans les 24 heures.',
    'contact.requestTitle': 'Demander un site web',
    'contact.requestDesc': 'Créez un compte et soumettez une demande détaillée. Suivez le statut et recevez des mises à jour.',
    'contact.requestCta': 'Soumettre une demande',
    'contact.requestCtaSignup': 'Créer un compte & demander',

    // Terms
    'terms.title': 'Conditions générales FlipForward',
    'terms.lastUpdated': 'Dernière mise à jour',
    'terms.intro': 'Les présentes conditions générales s\'appliquent à toutes les offres, devis et accords entre FlipForward (faisant partie de l\'entreprise individuelle Finn Vangronsveld / ATLAZ Records, KBO : BE1033868758) et le Client.',
    'terms.art1.title': 'Article 1 : Le modèle « Website as a Service » (WaaS)',
    'terms.art1.p1': 'FlipForward fournit le design web et l\'hébergement via un modèle d\'abonnement. Le Client n\'achète pas le site web mais obtient un droit d\'utilisation exclusif tant que l\'abonnement mensuel est actif.',
    'terms.art1.p2': 'Tous les sites web développés par FlipForward, y compris le code, les designs, les implémentations IA et les licences, restent à tout moment la propriété intellectuelle de FlipForward.',
    'terms.art2.title': 'Article 2 : Livraison et contenu',
    'terms.art2.p1': 'FlipForward vise à livrer le site web initial (Proof of Concept) dans les 5 jours ouvrables. Ce délai ne commence qu\'après le paiement de la facture de démarrage et la fourniture de tout le contenu requis (textes, images, logos) par le Client.',
    'terms.art2.p2': 'Si le Client ne fournit pas le matériel en temps voulu, cela peut retarder le délai de livraison. Cela ne donne droit à aucune réduction ou compensation.',
    'terms.art2.p3': 'Un maximum de deux (2) tours de feedback est inclus dans la construction initiale.',
    'terms.art3.title': 'Article 3 : Abonnement et maintenance',
    'terms.art3.p1': 'Après la mise en ligne ou l\'approbation du site web, l\'abonnement mensuel de 50 € (hors TVA) commence.',
    'terms.art3.p2': 'Cet abonnement comprend l\'hébergement, l\'enregistrement du nom de domaine, les coûts de licence des outils utilisés et la maintenance technique mineure jusqu\'à un maximum de 30 minutes par mois.',
    'terms.art3.p3': 'Les modifications qui dépassent le cadre initial ou prennent plus de 30 minutes (travail supplémentaire) seront facturées après consultation au tarif horaire de 100 € (hors TVA).',
    'terms.art4.title': 'Article 4 : Paiement et défaut',
    'terms.art4.p1': 'Les factures doivent être payées dans les 14 jours suivant la date de facturation.',
    'terms.art4.p2': 'En cas de non-paiement après ce délai, le Client recevra un rappel. Si le paiement reste impayé, FlipForward est en droit de mettre le site web (temporairement) hors ligne jusqu\'au paiement intégral.',
    'terms.art4.p3': 'Les frais de démarrage doivent être payés avant le début des travaux.',
    'terms.art5.title': 'Article 5 : Résiliation de l\'abonnement',
    'terms.art5.p1': 'L\'abonnement peut être résilié mensuellement par le Client.',
    'terms.art5.p2': 'En cas de résiliation, le droit d\'utilisation visé à l\'Article 1 expire. Le site web et les fichiers associés seront définitivement supprimés des serveurs à la fin de la période de facturation en cours. Aucun transfert de code ou de fichiers du site web au Client n\'aura lieu.',
    'terms.art6.title': 'Article 6 : Responsabilité',
    'terms.art6.p1': 'FlipForward s\'efforce de faire fonctionner le site web et les outils IA liés de manière optimale, mais ne peut garantir une disponibilité à 100 % ou un fonctionnement sans erreur des logiciels (IA) externes.',
    'terms.art6.p2': 'La responsabilité de FlipForward pour les dommages directs ou indirects est à tout moment limitée au montant de la facture des trois (3) derniers mois de la mission concernée.',
    'terms.art7.title': 'Article 7 : Droit applicable',
    'terms.art7.p1': 'Tous les accords entre FlipForward et le Client sont exclusivement régis par le droit belge. Les litiges seront soumis au tribunal compétent du district où FlipForward est établi.',

    // Privacy Policy
    'privacy.title': 'Politique de confidentialité FlipForward',
    'privacy.lastUpdated': 'Dernière mise à jour',
    'privacy.intro': 'FlipForward (faisant partie d\'ATLAZ Records, KBO : BE1033868758) accorde de l\'importance à votre vie privée. Dans cette politique de confidentialité, nous expliquons quelles données personnelles nous collectons, pourquoi nous le faisons et quels sont vos droits.',
    'privacy.section1.title': '1. Quelles données collectons-nous ?',
    'privacy.section1.text': 'Lorsque vous remplissez notre formulaire de contact ou souscrivez un abonnement de design web chez nous, nous collectons les données suivantes :',
    'privacy.section1.items': 'Prénom et nom|Nom de l\'entreprise et numéro KBO/TVA|Adresse e-mail et numéro de téléphone|Données de facturation et de paiement',
    'privacy.section2.title': '2. Pourquoi collectons-nous ces données ?',
    'privacy.section2.text': 'Nous utilisons vos données exclusivement pour :',
    'privacy.section2.items': 'La création, l\'hébergement et la maintenance de votre site web.|Le traitement des paiements et la facturation (via notre partenaire Dexxter).|Vous contacter au sujet de votre projet ou questions de support.',
    'privacy.section3.title': '3. Combien de temps conservons-nous vos données ?',
    'privacy.section3.text': 'Nous ne conservons pas vos données personnelles plus longtemps que strictement nécessaire pour atteindre les objectifs pour lesquels vos données sont collectées. Les données de facturation sont légalement conservées pendant 7 ans conformément à la législation fiscale belge.',
    'privacy.section4.title': '4. Partage des données avec des tiers',
    'privacy.section4.text': 'FlipForward ne vend pas vos données à des tiers et ne les fournit que si cela est nécessaire à l\'exécution de notre accord avec vous (par exemple, hébergeurs ou logiciel de facturation) ou pour se conformer à une obligation légale.',
    'privacy.section5.title': '5. Vos droits (RGPD)',
    'privacy.section5.text': 'Vous avez le droit de consulter, corriger ou supprimer vos données personnelles. De plus, vous avez le droit de retirer tout consentement au traitement des données ou de vous opposer au traitement de vos données personnelles par FlipForward. Envoyez un e-mail à : info@flipforward.be.',
    'privacy.section6.title': '6. Cookies',
    'privacy.section6.text': 'Notre site web utilise des cookies fonctionnels pour assurer le fonctionnement optimal du site. Nous utilisons également des outils d\'analyse pour analyser comment les visiteurs utilisent notre site web.',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
